### ISSUE TITLE
Don't change \n to an actual newline

### ISSUE THREAD

**Issue by aboyton** [prettier/plugin-php#29]
First up, awesome work on this project, I'm really excited. I seem to recall there was some discussion about this for JavaScript but I can't find the issue.

Right now this converts
```php
$foo = "hello\nworld"
```
into
```php
$foo = "hello
world"
```

Personally I think it is nicer to leave the `\n` alone.

**Comment by mgrip** [comment]
🙏 Thanks for finding these issues @aboyton! Keep em coming 😉

**Comment by aboyton** [comment]
No worries. Not sure how much time I'll have to help with the coding, but very happy to help with the testing. I've got a reasonably large PHP codebase to run this on.

**Comment by evilebottnawi** [comment]
WIP

**Comment by evilebottnawi** [comment]
@mgrip sorry, did not have time today, tomorrow I will do

**Comment by mgrip** [comment]
No worries, thanks!

**Comment by mgrip** [comment]
@evilebottnawi fixed with #136

**Comment by aboyton** [comment]
This still appears to be happening for me in certain cases, in particular if I have a variable directly in a string like below. I'm happy to open a new issue if you'd like.

```php
printf("Query run in $queryTimeTaken seconds.\n");
```

**Comment by evilebottnawi** [comment]
Done in https://github.com/prettier/plugin-php/pull/263
