### ISSUE TITLE
Ugly output `new` node with comment

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/plugin-php#318]
Input:
```php

// Comment
throw new ClassName( // Comment
    1, // Comment
    // Comment
    2 // Comment
); // Comment

/* Comment */
throw new ClassName( /* Comment */
    /* Comment */ 1, /* Comment */
    /* Comment */
    /* Comment */ 2 /* Comment */
    /* Comment */); /* Comment */
```
Output:
```php
// Comment
throw new ClassName(// Comment
1, // Comment // Comment
2); // Comment // Comment

/* Comment */
throw new ClassName(/* Comment */ /* Comment */
1, /* Comment */ /* Comment */
/* Comment */
2); /* Comment */
/* Comment */ /* Comment */
```

**Comment by mgrip** [comment]
fixed in #319

**Comment by evilebottnawi** [comment]
@mgrip no, we just output `comment` , it is not fixed :smile:
